### ISSUE TITLE
It does not support chapter.

### ISSUE THREAD

**Issue by csukuangfj** [matze/vim-tex-fold#11]
It supports \section, \subsection and so on, but \chapter is somehow not supported .

**Comment by matze** [comment]
Correct. But I also don't think it's a good idea to have *multiple* chapters in a *single* `.tex` file. I guess, people will come back at me if I add that and cause sluggish performance. But you are free to fork the plugin and add the relevant match [here](https://github.com/matze/vim-tex-fold/blob/master/after/ftplugin/tex.vim#L57).

**Comment by csukuangfj** [comment]
@matze 
Thank you for the fast response.

Should I return 0 for \chapter?

**Comment by matze** [comment]
No, see the [fold](http://vimdoc.sourceforge.net/htmldoc/fold.html) documentation. 0 means no fold, the first fold level starts at 1.

**Comment by csukuangfj** [comment]
Got it. Thanks.
