### ISSUE TITLE
Problems of speed

### ISSUE THREAD

**Issue by stanislas-brossette** [matze/vim-tex-fold#9]
Hello,
I'm having some speed issues when using this great plugin on large files (1000 lines) that contain a lot of equations.
For example, inserting some random text (not equations) resulted in that kind of profiling results:
```
FUNCTIONS SORTED ON TOTAL TIME
count  total (s)   self (s)  function
38717   6.227731             TeXFold()
   63   0.179688             provider#python3#Call()
   62   0.106460             UltiSnips#TrackChange()
    1   0.075056   0.075028  UltiSnips#ExpandSnippetOrJump()
   19   0.003085             <SNR>41_Highlight_Matching_Pair()
    1   0.000553   0.000076  neomake#CursorMoved()
    1   0.000263             neomake#signs#PlaceVisibleSigns()
    2   0.000238             TeXFoldText()
    1   0.000214             neomake#EchoCurrentError()
    1   0.000028             <SNR>76_compensate_for_pum()

FUNCTIONS SORTED ON SELF TIME
count  total (s)   self (s)  function
38717              6.227731  TeXFold()
   63              0.179688  provider#python3#Call()
   62              0.106460  UltiSnips#TrackChange()
    1   0.075056   0.075028  UltiSnips#ExpandSnippetOrJump()
   19              0.003085  <SNR>41_Highlight_Matching_Pair()
    1              0.000263  neomake#signs#PlaceVisibleSigns()
    2              0.000238  TeXFoldText()
    1              0.000214  neomake#EchoCurrentError()
    1   0.000553   0.000076  neomake#CursorMoved()
    1              0.000028  <SNR>76_compensate_for_pum()
```

Is there a way to have the plugin evaluate the folds only once when opening the file? Or force it to evaluate only 1 or 2 levels deep of folding so that it doesn't get stuck in complicated equations (which I think are responsible for the lag here)?
(NB: my machine is not slow)

**Comment by matze** [comment]
> Is there a way to have the plugin evaluate the folds only once when opening the file? 

This is not how folding works in Vim and frankly wouldn't make much sense considering that you can add more folds arbitrarily and dynamically.

> Or force it to evaluate only 1 or 2 levels deep of folding so that it doesn't get stuck in complicated equations?

Again, that's unfortunately not how it could work using expression-based folding. The problem is that we try to pattern match *each* line to tell Vim the current depth. Matching seven patterns on 1000 lines can quickly slow.

Since you have many `\begin{}\end{}` environments, would it be helpful to disable matching those (losing folds then of course)?

**Comment by stanislas-brossette** [comment]
This could probably help, thanks.
In the documentation, I see the option to **add** additional environments to fold.
let g:tex_fold_additional_envs = ['example']
How can I **remove** environments to fold?

**Comment by matze** [comment]
You cannot, except for patching that list.

**Comment by matze** [comment]
I pushed a change that allows you to disable matching environments by setting `g:tex_fold_ignore_envs` to 1. If it helps, please close this issue.

**Comment by stanislas-brossette** [comment]
I compared the profiling results for the same sequence of input with and without this option.
teXFold gets called exactly the same number of times, but is slower with the option 
`let g:tex_fold_ignore_envs = 1`

Profile with tex_fold_ignore_envs = 0 gives:
```
FUNCTIONS SORTED ON SELF TIME
count  total (s)   self (s)  function
13780              2.077274  TeXFold()
```

Profile with tex_fold_ignore_envs = 0 gives:
```
FUNCTIONS SORTED ON SELF TIME
count  total (s)   self (s)  function
13780              2.865933  TeXFold()
```
 
I'll try again with a minimal vimrc and example file in the next few days.

**Comment by matze** [comment]
> but is slower with the option let g:tex_fold_ignore_envs = 1

That's because I am obviously not good at simple logics … should be fixed now. But that is still quite a large number.

**Comment by stanislas-brossette** [comment]
This last fix does it. Much better performances now. Thanks.
